// File generated manually (normally auto-generated by FlutterFire CLI)

import 'package:firebase_core/firebase_core.dart';
import 'package:flutter/foundation.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  /// 🔹 WEB CONFIG
  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "YOUR_WEB_API_KEY",
    authDomain: "forecast-l100.firebaseapp.com",
    projectId: "forecast-l100",
    storageBucket: "forecast-l100.appspot.com",
    messagingSenderId: "855884989852",
    appId: "1:855884989852:web:3156db66dbe33d29d23459",
  );

  /// 🔹 ANDROID CONFIG
  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "YOUR_ANDROID_API_KEY",
    appId: "1:855884989852:android:011a5345b6ac17e9d23459",
    messagingSenderId: "855884989852",
    projectId: "forecast-l100",
    storageBucket: "forecast-l100.appspot.com",
  );
}
